FROM            ec2-deploy:base

ENV             PROJECT_DIR     /srv/project


#Ngnix , supervisor install
RUN             apt -y install nginx supervisor

ENV             BUILD_MODE  dev

# Copy projects files
COPY            .   ${PROJECT_DIR}
WORKDIR         ${PROJECT_DIR}

# Virtalenv path
RUN             export VENV_PATH=$(pipenv --venv); echo $VENV_PATH;
#ENV             VENV_PATH $VENV_PATH


# Ngnix config
RUN         cp -f ${PROJECT_DIR}/.config/${BUILD_MODE}/nginx.conf \
                  /etc/nginx/nginx.conf && \

            # available에 nginx_app.conf파일 복사
            cp -f ${PROJECT_DIR}/.config/${BUILD_MODE}/nginx_app.conf \
                        /etc/nginx/sites-available/ && \

                # 이미 sites-enabled에 있던 모든 내용 삭제
                rm -f   /etc/nginx/sites-enabled/* && \

                # available에 있는 nginx_app.conf를 enabled로 링크.
                ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                        /etc/nginx/sites-enabled

# Supervisor
RUN             cp -f ${PROJECT_DIR}/.config/${BUILD_MODE}/supervisor_app.conf \
                        /etc/supervisor/conf.d
# RUN supervisor
CMD             supervisord -n
## Run uWSGI (CMD)
#CMD             pipenv run uwsgi --ini ${PROJECT_DIR}/.config/uwsgi_http.ini

# RUN Ngnix
#CMD             nginx -g 'daemon off;'